server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 9000
spring:
  datasource:
    username: root
    password: root
#    url: jdbc:mysql://172.17.8.102:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
#spring:
#  datasource:
#    username: ACTIVITI
#    password: 123456789
#    jdbc-url: jdbc:dm://192.168.1.39:5236:DAMENG
#    driver-class-name: dm.jdbc.driver.DmDriver
    #日志的相关配置
logging:
  level:
    root: info
#日志的相关配置
spring.activiti.history-level: full
spring.activiti.db-history-used: true
# spring-activiti
# 自动部署验证设置:true-开启（默认）、false-关闭
spring.activiti.check-process-definitions: false


